apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  name: shaarli-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
  volumeMode: Filesystem
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
