apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sdntrs-quest
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: sdntrs-quest
spec:
  ingressClassName: sdntrs-quest
  tls:
    - hosts:
        - links.sdntrs.quest
      secretName: links-sdntrs-quest
  rules:
    - host: links.sdntrs.quest
      http:
        paths:
          - backend:
              service:
                port:
                  name: http
            path: /
            pathType: Prefix
