
---
# Source: metallb/templates/webhooks.yaml
apiVersion: v1
kind: Secret
metadata:
  name: webhook-server-cert
  labels:
    app.kubernetes.io/name: metallb
    app.kubernetes.io/instance: metallb
    app.kubernetes.io/version: "v0.14.3"
    app.kubernetes.io/managed-by: kustomize
---
