
---
# Source: metallb/templates/service-accounts.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metallb-speaker
  labels:
    app.kubernetes.io/name: metallb
    app.kubernetes.io/instance: metallb
    app.kubernetes.io/version: "v0.14.3"
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/component: speaker
