apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overseerr-storage
  namespace: overseerr
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
