---
apiVersion: v1
kind: Namespace
metadata:
  name: etc-links
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shaarli-storage
  namespace: etc-links
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: shaarli
  namespace: etc-links
  labels:
    app: shaarli
spec:
  containers:
  - name: shaarli
    image: ghcr.io/shaarli/shaarli:latest
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: data
      mountPath: /var/www/shaarli/data
    - name: cache
      mountPath: /var/www/shaarli/cache
    ports:
    - containerPort: 80
      name: http
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: shaarli-storage
  - name: cache
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: sdntrs-quest
    external-dns.alpha.kubernetes.io/hostname: links.sdntrs.quest
  labels:
    app: etc-links
  name: etc-links
  namespace: etc-links
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: shaarli
  type: LoadBalancer
