apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sticky-notes
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  storageClassName: grouse-non-raid
status:
