apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: smb
provisioner: smb.csi.k8s.io
parameters:
  source: "//grouse.burrow.lab.sudonters.com/shaarli"
  csi.storage.k8s.io/node-stage-secret-name: "shaarli"
  csi.storage.k8s.io/node-stage-secret-namespace: "smb-csi"
  createSubDir: "true"
reclaimPolicy: Retain      # only Retain is supported
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1001
  - gid=1001

