---
images:
  - name: fireflyiii/data-importer
    newTag: version-0.8.0
resources:
  - ../../../../manifests/firefly-iii
  - namespace.yaml
  - brrws-xyz-ingress.yaml
secretGenerator:
  - name: access-key
    type: Opaque
    literals:
      - VANITY_URL=https://cream.sdntrs.quest
  - name: app-key
    type: Opaque
    literals:
      - APP_KEY=FUmWrgswVdgB9R2ATQEn4phRC89ApXT6
  - name: database-access
    literals:
      - DB_HOST=firefly-iii-mysql
      - DB_CONNECTION=mysql
      - DB_DATABASE=fireflyiii
      - DB_USERNAME=root
      - DB_PASSWORD=7f8sdBpGJnGxZr4chRLfs22TXipE8uCo
labels:
  - pairs:
      "app.kubernetes.io/part-of": "firefly-iii"
      "app.kubernetes.io/instance": "cream.sdntrs.quest"
transformers:
  - applyNamespace.yaml
patches:
  - target:
      kind: PersistentVolumeClaim
      name: firefly-iii-upload-claim
    patch: |-
      - op: add
        path: "/spec/storageClassName"
        value: local-path
  - target:
      kind: PersistentVolumeClaim
      name: mysql-pv-claim
    patch: |-
      - op: add
        path: "/spec/storageClassName"
        value: local-path
  - target:
      kind: Deployment
      name: firefly-iii
    patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/envFrom"
        value: 
        - secretRef: 
            name: "app-key"
        - secretRef: 
            name: "database-access"
  - target:
      kind: Deployment
      name: firefly-iii-importer
    patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/envFrom"
        value: 
          - secretRef:
              name: "access-key"
  - target:
      kind: Ingress
      name: brrws-xyz
    patch: |-
      - op: add
        path: "/spec/ingressClassName"
        value: brrws-xyz
      - op: add
        path: "/metadata/annotations/cert-manager.io~1cluster-issuer"
        value: brrws-xyz
      - op: replace
        path: "/spec/rules/0/host"
        value: cream.brrws.xyz
      - op: add
        path: "/spec/tls"
        value:
          - hosts:
              - cream.brrws.xyz
            secretName: cream-brrws-xyz
  - target:
      kind: Ingress
      name: firefly-iii-importer-ingress
    patch: |-
      - op: add
        path: "/spec/ingressClassName"
        value: sdntrs-quest
      - op: add
        path: "/metadata/annotations/cert-manager.io~1cluster-issuer"
        value: sdntrs-quest
      - op: replace
        path: "/spec/rules/0/host"
        value: cream-import.sdntrs.quest
      - op: add
        path: "/spec/tls"
        value:
          - hosts:
              - cream-import.sdntrs.quest
            secretName: cream-import-sdntrs.quest
  - target:
      kind: Ingress
      name: firefly-iii-ingress
    patch: |-
      - op: replace
        path: "/spec/rules/0/host"
        value: cream.sdntrs.quest
      - op: add
        path: "/spec/ingressClassName"
        value: sdntrs-quest
      - op: add
        path: "/metadata/annotations/cert-manager.io~1cluster-issuer"
        value: sdntrs-quest
      - op: add
        path: "/spec/tls"
        value:
          - hosts:
              - cream.sdntrs.quest
            secretName: cream-sdntrs-quest
  - target:
      kind: Deployment
      name: firefly-iii-mysql
    patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env"
        value: 
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-access
                key: DB_PASSWORD
