resources:
  - ../../../../manifests/shaarli
  - ./resources/persistentvolumeclaim.yaml
  - ./resources/routing.yaml
patches:
  - path: patches/persistentVolume.yaml
namespace: etc-links
namePrefix: etc-links-
commonLabels:
  app.kubernetes.io/instance: etc-links
  app.kubernetes.io/name: shaarli
labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
    includeTemplates: true
replacements:
  - source:
      kind: PersistentVolumeClaim
      name: shaarli
      fieldPath: metadata.name
    targets:
      - select:
          name: shaarli
          kind: Deployment
        fieldPaths:
          - spec.template.spec.volumes.[name=data].persistentVolumeClaim.claimName
        options:
          create: true
  - source:
      kind: Service
      name: shaarli
      fieldPath: metadata.name
    targets:
      - select:
          kind: Ingress
          name: sdntrs-quest
        fieldPaths:
          - spec.rules.*.http.paths.*.backend.service.name
        options:
          create: true
