apiVersion: v1
kind: Service
metadata:
  name: firefly-iii-mysql
  labels:
    app: firefly-iii
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: mysql
  selector:
    app: firefly-iii
    tier: mysql
