apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shaarli
  name: shaarli
spec:
  template:
    spec:
      volumes:
        - name: cache
          emptyDir: {}
        - name: data
          persistentVolumeClaim:
            claimName: default
