apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns
  namespace: sdntrs-quest
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  - nodes
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - extensions
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: sdntrs-quest
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
  namespace: sdntrs-quest
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
- kind: ServiceAccount
  name: external-dns
  namespace: sdntrs-quest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: sdntrs-quest
spec:
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.k8s.io/external-dns/external-dns:v0.14.0
        args:
        - --registry=txt
        - --txt-prefix=burroughs-
        - --txt-owner-id=burroughs-
        - --provider=rfc2136
        - --rfc2136-zone=sdntrs.quest
        - --rfc2136-host=10.31.0.2
        - --rfc2136-port=53
        - --rfc2136-tsig-secret=fjeCBFq5Cjma5Wiq2F7OLgaNm0Nqu9u+AWV16hf9jIo=
        - --rfc2136-tsig-secret-alg=hmac-sha256
        - --rfc2136-tsig-keyname=rndc-key
        - --rfc2136-tsig-axfr
        - --domain-filter=sdntrs.quest
        - --source=ingress
        - --source=service
